# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Whatsapp-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'IQKeyboardManagerSwift'

  # Pods for Whatsapp-Demo

  target 'Whatsapp-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Whatsapp-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
